### ISSUE TITLE
extract_base_hudfiles.bat

### ISSUE THREAD

**Issue by sammybun** [Stochast1c/solarhud#3]
You might want to include the HLExtract folder with the .exe and .dll files in the hud for the extraction to work.

[HLExtract.zip](https://github.com/Stochast1c/solarhud/files/184781/HLExtract.zip)

**Comment by Stochast1c** [comment]
I had the directory there, but my global gitignore was ignoring .exe and .dll's so it never wanted to add the directory.  Thanks for the heads up, I fixed it.
